# Generated by Django 5.0.6 on 2024-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIL1_2324_9_app', '0007_rename_receiver_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
