# Generated by Django 5.0.6 on 2024-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIL1_2324_9_app', '0008_friendship_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=12),
        ),
    ]
